FROM node:20-bookworm-slim

# Create app directory
WORKDIR /usr/src/app

# Update package repositories and install required packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Accept build arguments
ARG NPM_TOKEN
ARG VOICE_TOKEN
ARG VOICE_TWILIO_TOKEN

COPY .npmrc_ .npmrc

# Set environment variable based on build argument
ENV VOICE_TOKEN=${VOICE_TOKEN}
ENV VOICE_TWILIO_TOKEN=${VOICE_TWILIO_TOKEN}

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install --production

RUN rm -f .npmrc

# Bundle app source
COPY . .

EXPOSE 3000

CMD [ "npm", "start" ]

